version: '3.8'

services:
  main:
    container_name: main
#    image: node:16.15-alpine
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
      target: development
    env_file:
        - .env
    working_dir: /app
    volumes:
      - .:/app
#      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
#    image: postgres:14.4-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
